// src/pages/Portfolio/components/SectionAbout/index.tsx
import { Trans, useTranslation } from 'react-i18next'

import Section from '../../../../components/Section'

import About from './AboutRow'

import ipbImage from '../../../../assets/ipb_estig_ap_1.jpg'
import utfprImage from '../../../../assets/utfpr-nova-2022jpg.jpg'
import atlaEnsinoImage from '../../../../assets/atla.jpg'
import viptechImage from '../../../../assets/viptech.png'

const components = [<p />, <p />, <b />]

export default function SectionAbout() {
  const {t} = useTranslation()
  return (
    <Section id="about" className="flex-1 py-5 md:py-10">
      <Section.Title title={t("about.title")} />
      <Section.Content>
        <About>
          <About.Image
            link="https://www.utfpr.edu.br/campus/campomourao"
            src={utfprImage}
            alt="Universidade Tecnológica Federal do Paraná (UTFPR)"
          />
          <About.Text>
            <p>
              <Trans i18nKey="about.utfpr.1" values={{ age: age() }} components={components} />
            </p>
            <p>
              <Trans i18nKey="about.utfpr.2" components={components} />
            </p>
            <p>
              <Trans i18nKey="about.utfpr.3" components={components} />
            </p>
          </About.Text>
        </About>
        <About>
          <About.Image link="https://atlaensino.com/public/landing" src={atlaEnsinoImage} alt="ATLA Ensino" />
          <About.Text>
            <p>
              <Trans i18nKey="about.atla.1" components={components} />
            </p>
            <p>
              <Trans i18nKey="about.atla.2" components={components} />
            </p>
            <p>
              <Trans i18nKey="about.atla.3" components={components} />
            </p>
          </About.Text>
        </About>
        <About>
          <About.Image link="https://www.viptech.com.br" src={viptechImage} alt="Viptech" />
          <About.Text>
            <p>
              <Trans i18nKey="about.viptech.1" components={components} />
            </p>
            <p>
              <Trans i18nKey="about.viptech.2" components={components} />
            </p>
          </About.Text>
        </About>
        <About>
          <About.Image link="https://ipb.pt/pt" src={ipbImage} alt="Instituto Politécnico de Bragança (IPB)" />
          <About.Text>
            <p>
              <Trans i18nKey="about.ipb.1" components={components} />
            </p>
            <p>
              <Trans i18nKey="about.ipb.2" components={components} />
            </p>
          </About.Text>
        </About>
      </Section.Content>
    </Section>
  )
}

function age() {
  const now = new Date()
  let age = now.getFullYear() - 1998 - 1
  if (now.getMonth() === 11 && now.getDate() >= 7) age++
  return `${age} anos`
}

// src/routes/SectionAbout.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { m } from '$lib/paraglide/messages';

	import Section from '../components/Section.svelte';
	import SectionTitle from '../components/SectionTitle.svelte';

	import AboutItem from '../components/AboutItem.svelte';
	import AboutImage from '../components/AboutImage.svelte';
	import AboutText from '../components/AboutText.svelte';

	import utfprImage from '$lib/images/utfpr-nova-2022jpg.jpg';
	import atlaEnsinoImage from '$lib/images/atla.jpg';
	import viptechImage from '$lib/images/viptech.png';
	import ipbImage from '$lib/images/ipb_estig_ap_1.jpg';

	const birthDate = new Date(1998, 11, 7);

	function computeAge(date: Date) {
		const now = date;
		let age = now.getFullYear() - birthDate.getFullYear();

		if (
			now.getMonth() < birthDate.getMonth() ||
			(now.getMonth() === birthDate.getMonth() && now.getDate() < birthDate.getDate())
		) {
			age--;
		}

		return m.years_old({ age }) as string;
	}

	// Build-time fallback
	let age = computeAge(new Date());

	onMount(() => {
		// recalculated on client
		age = computeAge(new Date());
		console.log({ age });
	});
</script>

<Section id="about">
	<SectionTitle>
		{m.about_title()}
	</SectionTitle>
	<div>
		<AboutItem>
			<AboutImage
				link="https://www.utfpr.edu.br/campus/campomourao"
				src={utfprImage}
				alt="Universidade Tecnológica Federal do Paraná (UTFPR)"
			/>
			<AboutText>
				<p>{@html m.about_utfpr_1({ age })}</p>
				<p>{@html m.about_utfpr_2()}</p>
				<p>{@html m.about_utfpr_3()}</p>
			</AboutText>
		</AboutItem>
		<AboutItem>
			<AboutImage
				link="https://atlaensino.com/public/landing"
				src={atlaEnsinoImage}
				alt="ATLA Ensino"
			/>
			<AboutText>
				<p>{@html m.about_atla_1()}</p>
				<p>{@html m.about_atla_2()}</p>
				<p>{@html m.about_atla_3()}</p>
			</AboutText>
		</AboutItem>
		<AboutItem>
			<AboutImage link="https://www.viptech.com.br" src={viptechImage} alt="Viptech" />
			<AboutText>
				<p>{@html m.about_viptech_1()}</p>
				<p>{@html m.about_viptech_2()}</p>
			</AboutText>
		</AboutItem>
		<AboutItem>
			<AboutImage
				link="https://ipb.pt/pt"
				src={ipbImage}
				alt="Instituto Politécnico de Bragança (IPB)"
			/>
			<AboutText>
				<p>{@html m.about_ipb_1()}</p>
				<p>{@html m.about_ipb_2()}</p>
			</AboutText>
		</AboutItem>
	</div>
</Section>
