// src/lib/components/I18nDropdown.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { goto } from '$app/navigation';

	import IconGlobe from './IconGlobe.svelte';

	let s = $state({ isOpen: false });

	function toggle() {
		s.isOpen = !s.isOpen;
	}

	function changeLanguage(lang: 'en' | 'pt-br') {
		goto(resolve(`/x/${lang}`));
	}
</script>

<div class="relative w-full" tabindex="-1">
	<button
		class="align-center flex w-full cursor-pointer justify-center"
		type="button"
		aria-label="Change Language"
		onclick={toggle}
	>
		<IconGlobe />
	</button>

	{#if s.isOpen}
		<ul
			class="absolute right-[50%] flex flex-col gap-3 rounded-md border border-gray-100 bg-white p-2 text-center text-lg text-black shadow-md"
		>
			<li>
				<button
					class="w-full cursor-pointer rounded px-1 hover:underline"
					onclick={() => changeLanguage('pt-br')}
				>
					PT
				</button>
			</li>

			<li>
				<button
					class="w-full cursor-pointer rounded px-1 hover:underline"
					onclick={() => changeLanguage('en')}
				>
					EN
				</button>
			</li>
		</ul>
	{/if}
</div>

// src/pages/Portfolio/components/SectionHeader/I18nDropdown.tsx
import { Globe } from 'lucide-react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'

export default function I18nDropdown() {
  const [isOpen, setIsOpen] = useState(false)
  const { i18n } = useTranslation()

  const changeLanguage = (lng: string) => {
    console.log(i18n)
    i18n.changeLanguage(lng)
    setIsOpen(false)
  }

  function renderDropdown() {
    if (!isOpen) return null
    return (
      <ul className="absolute right-0 text-black bg-white border border-grey-100 shadow-md rounded-md p-2 text-center flex flex-col gap-3 text-lg">
        <li className="cursor-pointer w-full hover:underline px-1 rounded" onClick={() => changeLanguage('pt')}>
          PT
        </li>
        <li className="cursor-pointer w-full hover:underline px-1 rounded" onClick={() => changeLanguage('en')}>
          EN
        </li>
      </ul>
    )
  }

  return (
    <div
      className="relative"
      onBlur={(e) => {
        if (!e.currentTarget.contains(e.relatedTarget)) {
          setIsOpen(false)
        }
      }}
      tabIndex={-1}
    >
      <button type="button" aria-label="Change Language" onClick={() => setIsOpen((it) => !it)}>
        <Globe absoluteStrokeWidth />
      </button>
      {renderDropdown()}
    </div>
  )
}
