// src/routes/SectionContactMe.svelte
<script>
	import { m } from '$lib/paraglide/messages';

	import Section from '../components/Section.svelte';
	import SectionTitle from '../components/SectionTitle.svelte';

	import SocialMidias from './SocialMidias.svelte';
</script>

<Section id="contact">
	<SectionTitle>
        {m.contacts_title()}
    </SectionTitle>
	<div class="flex flex-col lg:flex-row">
		<!-- <ContactMeForm /> -->
		<SocialMidias />
	</div>
</Section>

// src/pages/Portfolio/components/SectionContactMe/index.tsx
import Section from '../../../../components/Section'

// import ContactMeForm from './ContactMeForm'
import SocialMidias from './SocialMidias'

export default function SectionContactMe() {
  return (
    <Section className="py-5 md:py-10" id="contact">
      <Section.Title title="Entre em Contato" />
      <Section.Content className="flex flex-col lg:flex-row">
        {/* <ContactMeForm /> */}
        <SocialMidias />
      </Section.Content>
    </Section>
  )
}
